import {FwpfProp, MassgabenProp, SwsProp} from "@/features/Fwpfs/types";

export const fwpfs: FwpfProp[] = [
    {
        id: 1,
        label: "GUIV",
        sws: 4,
        prof: "Axel Platz",
        pruefung: "Kolloquium",
        vorkenntnisse: "keine",
        zusammenfassung: "Grundlagen der Gestaltung von Benutzeroberflächen mit Fokus auf visuelle Kommunikation und Interaktionsprinzipien.",
        auslastung: 85,
        fachbereich: "win",
    },
    {
        id: 2,
        label: "Interaktive Systeme",
        sws: 3,
        prof: "Dr. Lena Hoffmann",
        pruefung: "Projektarbeit",
        vorkenntnisse: "Grundlagen der Programmierung",
        zusammenfassung: "Konzepte und Methoden interaktiver Benutzungssysteme. Ziel ist die Entwicklung eigener Prototypen.",
        auslastung: 90,
        fachbereich: "in",
    },
    {
        id: 3,
        label: "Webtechnologien",
        sws: 5,
        prof: "Prof. Jens Schröder",
        pruefung: "schriftliche Klausur",
        vorkenntnisse: "HTML, CSS, JavaScript",
        zusammenfassung: "Moderne Webentwicklung mit aktuellen Technologien, Frameworks und responsivem Design.",
        auslastung: 95,
        fachbereich: "min",
    },
    {
        id: 4,
        label: "Usability Engineering",
        sws: 2,
        prof: "Sabine Müller",
        pruefung: "Hausarbeit + Präsentation",
        vorkenntnisse: "Mensch-Computer-Interaktion",
        zusammenfassung: "Methoden zur Bewertung und Verbesserung der Gebrauchstauglichkeit interaktiver Systeme.",
        auslastung: 70,
        fachbereich: "win",
    },
    {
        id: 5,
        label: "Mobile App Entwicklung",
        sws: 4,
        prof: "Prof. Dr. Karim Al-Hakim",
        pruefung: "praktische Prüfung",
        vorkenntnisse: "OOP, Java oder Swift",
        zusammenfassung: "Konzeption und Entwicklung mobiler Applikationen für Android und iOS mit Fokus auf User Experience.",
        auslastung: 88,
        fachbereich: "in",
    },
    {
        id: 6,
        label: "Data Visualisierung",
        sws: 3,
        prof: "Dr. Julia Richter",
        pruefung: "Projekt + Bericht",
        vorkenntnisse: "Grundlagen Statistik",
        zusammenfassung: "Techniken und Werkzeuge zur visuellen Darstellung komplexer Daten und Zusammenhänge.",
        auslastung: 76,
        fachbereich: "win",
    },
    {
        id: 7,
        label: "Game Design Basics",
        sws: 4,
        prof: "Timo Bernhardt",
        pruefung: "Portfolio",
        vorkenntnisse: "keine",
        zusammenfassung: "Einführung in die Grundlagen der Spieleentwicklung mit Fokus auf Interaktionsdesign und Spielerführung.",
        auslastung: 80,
        fachbereich: "min",
    },
    {
        id: 8,
        label: "3D-Modellierung",
        sws: 3,
        prof: "Katharina Meier",
        pruefung: "praktische Abgabe",
        vorkenntnisse: "Grundkenntnisse Grafikdesign",
        zusammenfassung: "Erstellung und Texturierung einfacher 3D-Modelle für Anwendungen in UI/UX und Gaming.",
        auslastung: 65,
        fachbereich: "min",
    },
    {
        id: 9,
        label: "Voice User Interfaces",
        sws: 2,
        prof: "Prof. Thomas Engel",
        pruefung: "Präsentation",
        vorkenntnisse: "Usability Engineering",
        zusammenfassung: "Gestaltung sprachgesteuerter Interfaces mit Fokus auf Dialogführung und semantische Interaktion.",
        auslastung: 58,
        fachbereich: "win",
    },
    {
        id: 10,
        label: "User Research",
        sws: 3,
        prof: "Dr. Miriam Krauß",
        pruefung: "Bericht + Reflexion",
        vorkenntnisse: "MCI, Statistik",
        zusammenfassung: "Qualitative und quantitative Methoden zur Nutzerforschung zur Gestaltung besserer Interfaces.",
        auslastung: 73,
        fachbereich: "win",
    },
    {
        id: 11,
        label: "Barrierefreie Systeme",
        sws: 2,
        prof: "Laura Steiner",
        pruefung: "Klausur",
        vorkenntnisse: "Grundlagen HCI",
        zusammenfassung: "Entwicklung inklusiver digitaler Anwendungen für Menschen mit Einschränkungen.",
        auslastung: 62,
        fachbereich: "min",
    },
    {
        id: 12,
        label: "Animation & Motion Design",
        sws: 4,
        prof: "Felix Braun",
        pruefung: "Animationsprojekt",
        vorkenntnisse: "Grundkenntnisse Design",
        zusammenfassung: "Einführung in die Gestaltung von Mikrointeraktionen und animierten UI-Elementen.",
        auslastung: 82,
        fachbereich: "min",
    },
    {
        id: 13,
        label: "AR/VR Interfaces",
        sws: 5,
        prof: "Dr. Nora Lüders",
        pruefung: "Projekt",
        vorkenntnisse: "3D-Modellierung, Unity empfohlen",
        zusammenfassung: "Entwicklung von Benutzeroberflächen für immersive Augmented- und Virtual-Reality-Umgebungen.",
        auslastung: 91,
        fachbereich: "min",
    },
    {
        id: 14,
        label: "Interkulturelles Interface Design",
        sws: 2,
        prof: "Prof. Dr. Ahmed Yılmaz",
        pruefung: "Hausarbeit",
        vorkenntnisse: "MCI",
        zusammenfassung: "Berücksichtigung kultureller Unterschiede bei der Gestaltung von UI/UX für internationale Zielgruppen.",
        auslastung: 47,
        fachbereich: "win",
    },
    {
        id: 15,
        label: "UI Prototyping",
        sws: 3,
        prof: "Hannah Weigel",
        pruefung: "Prototyp + Review",
        vorkenntnisse: "Grundlagen HCI",
        zusammenfassung: "Schnelles Erstellen und Testen von User Interfaces mit Hilfe von Prototyping-Tools.",
        auslastung: 77,
        fachbereich: "win",
    },
    {
        id: 16,
        label: "Psychologie in der UI",
        sws: 2,
        prof: "Dr. Eva Kühn",
        pruefung: "Essay",
        vorkenntnisse: "Grundlagen Psychologie",
        zusammenfassung: "Wahrnehmung, Entscheidungsverhalten und Kognition im Zusammenhang mit Interface-Gestaltung.",
        auslastung: 66,
        fachbereich: "win",
    },
    {
        id: 17,
        label: "Designsysteme & Komponenten",
        sws: 3,
        prof: "Michael Harz",
        pruefung: "Komponentenprojekt",
        vorkenntnisse: "CSS, JS",
        zusammenfassung: "Aufbau und Pflege konsistenter Designsysteme zur skalierbaren UI-Entwicklung.",
        auslastung: 84,
        fachbereich: "in",
    },
    {
        id: 18,
        label: "Responsive Design",
        sws: 2,
        prof: "Clara Weiss",
        pruefung: "Online-Test",
        vorkenntnisse: "HTML/CSS",
        zusammenfassung: "Gestaltung von Interfaces, die sich flexibel an verschiedene Bildschirmgrößen und Geräte anpassen.",
        auslastung: 60,
        fachbereich: "min",
    },
    {
        id: 19,
        label: "Microinteractions",
        sws: 2,
        prof: "Jakob Voss",
        pruefung: "Kleines Projekt",
        vorkenntnisse: "Animation & UX-Grundlagen",
        zusammenfassung: "Design subtiler Animationen und Reaktionen im Interface für eine verbesserte Nutzererfahrung.",
        auslastung: 79,
        fachbereich: "min",
    },
    {
        id: 20,
        label: "Interface Testing",
        sws: 3,
        prof: "Lisa Bergmann",
        pruefung: "Testdokumentation",
        vorkenntnisse: "Prototyping & UX",
        zusammenfassung: "Planung, Durchführung und Auswertung von Usability-Tests mit echten Nutzergruppen.",
        auslastung: 68,
        fachbereich: "win",
    }
];



export const massgaben: MassgabenProp = {
    studiengang: "Bachelor Wirtschaftsinformatik, Studienordnung ab 2009/10",
    voraussetzung: "Studierende dieses Studiengangs können fachwissenschaftliche Wahlpflichtfächer (FWPF) nur ableisten, wenn Sie alle Fächer des 1. Studienabschnitts bestanden haben. Die FWPF verteilen sich auf die Semester 6 und 7.",
    infos: "Sie haben FWPF im Umfang von 20 Leistungspunkten (16 SWS) zu belegen, von denen in der Summe 15 LP (12 SWS) aus den Modulen im Schwerpunkt zu erbringen sind.\n",
    zusatzinfo: "Weitere Fächer können Sie als Wahlfach belegen.",
    hinweis: "Die Einschreibung ist abgeschlossen.",
    stundenplaninfo: 'Um Ihnen die Entscheidung zu erleichtern, sind die [Stundenpläne des kommenden Semesters] bei Einschreibungsbeginn verfügbar!'
}

export const swsConfig: SwsProp = {
    sws: 'Bitte geben Sie an, wie viele Semesterwochenstunden Sie im nächsten Semester belegen möchten. Bitte achten Sie darauf, Summen anzugeben, die durch Fächerkombinationen erreichbar sind. Nur so ist es möglich, Ihnen eine möglichst optimale Fächerbelegung ermöglichen zu können.',
    info: 'Die Semesterwochenstunden von Wahlfächern bleiben an dieser Stelle unberücksichtigt. Darum rechnen Sie diese bitte nicht mit ein!',
    belegt: 1,
    min: 3,
}