import Head from "next/head";
import Layout from "@/components/Layout/Layout";
import Page from "@/features/Page";
import { ThemeProvider, createTheme } from '@mui/material/styles';

const darkTheme = createTheme({
    palette: {
        mode: 'light',
        primary: {
            main: '#050000',
        },
    },
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <ThemeProvider theme={darkTheme}>
            <Layout>
                <Page/>
            </Layout>
        </ThemeProvider>

    </>
  );
}
